spring:
  data:
    jpa:
      repositories:
        enabled: 'true'
  jpa:
    database: mysql
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        
  datasource:
    password: thor
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/employee_management
    
logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %p %c %L : %m%n'
  file:
    name: E:/ECLIPSE/employee_management/logs/app.log
  level:
    root: info
  logback:
    rollingpolicy:
      max-file-size: 10mb